
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WOOutstandingGenerator
{

using System;
    using System.Collections.Generic;
    
public partial class InBuildStockDump
{

    public long ID { get; set; }

    public string PartNumber { get; set; }

    public decimal TotalOnHand { get; set; }

    public bool ExcludeMRP { get; set; }

    public bool Quarantined { get; set; }

    public string Stock { get; set; }

}

}
