//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOOutstandingGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectReportDbEntities : DbContext
    {
        public ConnectReportDbEntities()
            : base("name=ConnectReportDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WODump> WODumps { get; set; }
        public virtual DbSet<WODumpTotal> WODumpTotals { get; set; }
        public virtual DbSet<WOLineReport> WOLineReports { get; set; }
        public virtual DbSet<BOMShortageOwner> BOMShortageOwners { get; set; }
        public virtual DbSet<BOMShortageProductGroup> BOMShortageProductGroups { get; set; }
        public virtual DbSet<WOLineReport_PartsShortages> WOLineReport_PartsShortages { get; set; }
        public virtual DbSet<WOLineReport_WOPartsLevel> WOLineReport_WOPartsLevel { get; set; }
    }
}
