//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOOutstandingGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class WODump
    {
        public long WODump_ID { get; set; }
        public string WorksOrderNumber { get; set; }
        public decimal Outstanding { get; set; }
        public System.DateTime PlannedIssueDate { get; set; }
        public string ComponentPart { get; set; }
    }
}
